# Generated by Django 3.1.5 on 2021-04-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del pago')),
                ('descripcion', models.CharField(max_length=700, verbose_name='Descripcion')),
                ('monto', models.IntegerField(default=0, verbose_name='Monto a Pagar')),
                ('beca', models.TextField(choices=[('si', 'Si'), ('no', 'No')], verbose_name='Beca')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de registro de pago')),
                ('tipo_pago', models.TextField(choices=[('Inscripción', 'Inscripción'), ('Reinscripción', 'Reinscripción'), ('Intereses', 'Intereses'), ('Colegiatura', 'Colegiatura'), ('Conatancias', 'Conatancias'), ('Kardex', 'Kardex'), ('Credencial', 'Credencial')], verbose_name='Tipo de pago')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
            },
        ),
    ]
