# Generated by Django 3.2.2 on 2021-08-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del pago')),
                ('descripcion', models.CharField(max_length=700, verbose_name='Descripcion')),
                ('monto', models.IntegerField(default=0, verbose_name='Monto a Pagar')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de registro de pago')),
                ('tipo_Cobro', models.TextField(choices=[('Inscripción', 'Inscripción'), ('Reinscripción', 'Reinscripción'), ('Intereses', 'Intereses'), ('Colegiatura', 'Colegiatura'), ('Conatancias', 'Conatancias'), ('Kardex', 'Kardex'), ('Credencial', 'Credencial')], verbose_name='Tipo de pago')),
            ],
            options={
                'verbose_name': 'cobro',
                'verbose_name_plural': 'cobros',
            },
        ),
    ]
