# Generated by Django 3.1.7 on 2021-04-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('enrollment', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('adress', models.CharField(blank=True, max_length=80)),
                ('phoneNumber', models.CharField(blank=True, max_length=10)),
                ('grade', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('scholarship', models.IntegerField()),
            ],
        ),
    ]
