# Generated by Django 3.1.7 on 2021-04-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Students',
        ),
    ]
