# Generated by Django 3.1.7 on 2021-04-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20210410_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('domicilio', models.CharField(blank=True, max_length=80)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('grado', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('beca', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
