# Generated by Django 3.1.7 on 2021-04-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20210410_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='Alumno',
        ),
    ]
