# Generated by Django 3.1.7 on 2021-04-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_auto_20210410_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='domicilio',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
