# Generated by Django 3.1.7 on 2021-04-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '__first__'),
        ('pagos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('idReporte', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nombreDeudor', models.CharField(blank=True, max_length=100, null=True)),
                ('grado', models.IntegerField(default=0, verbose_name='Grado')),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidadDeudo', models.IntegerField(default=0, verbose_name='Monto a Pagar')),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.pago')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
    ]
