# Generated by Django 3.1.7 on 2021-04-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='idReporte',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
